In [1]:
import numpy as np
import pandas as pd

In [3]:
src = pd.read_excel("../assets/source/ORDER_REPORT.xlsx", skiprows=1)

/Users/yuchewang/opt/miniconda3/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [4]:
src

,BSN,Z13_TITLE,Z71_TEXT,Z71_OPEN_DATE,Z71_USER_NAME,Z71_DATA,Z30_BARCODE,Z30_ITEM_PROCESS_STATUS,ITEM_PROCESS_STATUS,Z30_PROCESS_STATUS_DATE,...,Z68_ORDERING_UNIT,Z68_ORDER_NUMBER,Z68_ORDER_TYPE,Z68_TOTAL_PRICE,Z68_ARRIVAL_STATUS,Z68_ORDER_STATUS_DATE_X,Z68_INVOICE_STATUS,Z68_VENDOR_CODE,Z68_LIBRARY_NOTE,Unnamed: 24
0,Bibiliographic System Number,Title,Arrival or not,Order Arrival Date,User who marked the item as Arrival,Item(s) Created,Barcode,Item Process Status Code,Item Process Status,IPS Changed Date?,...,Order Unit,Order Number,Order Type,Total Price,Arrival Status,Order Status Date?,Invoice Status,Vendor Code,Library Note,Mateial Format - PRN/VID
1,NaN,NaN,NaN,NaN,Shanghai Staff:,2 new items reported:,NaN,OR,On Order,NaN,...,NaN,NaN,Monograph,NaN,C - Complete,NaN,C - Complete,Local Vendor:,NaN,NaN
2,NaN,NaN,NaN,NaN,HEW,Set or volumns,NaN,GV,Out to vendor for digitization,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,P - Paid,CNP,NaN,NaN
3,NaN,NaN,NaN,NaN,ZHANGY,NaN,NaN,CT,"Arrived, but Uncataloged",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CEPIEC,NaN,NaN
4,NaN,NaN,NaN,NaN,GENERICSH,NaN,NaN,LT,Lost in Cataloging,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SBTSH,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,007377413,Republic /,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856740,,,20220128.0,...,NYUSH,NYUSH2022198,M,256.98,C,20220119,C,JDSH,"For Perry, Zee's Spring 2022 course. Ares#5294...",NaN
3563,004988629,HSK standard course =,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856765,,,20220128.0,...,NYUSH,NYUSH2022274,M,70.20,C,20220126,C,DANGSH,lost; replacement For Spring 2022 Course. [Leon],NaN
3564,004988629,HSK standard course =,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856773,,,20220128.0,...,NYUSH,NYUSH2022273,M,70.20,C,20220126,C,DANGSH,lost; replacement For Spring 2022 Course. Are...,NaN
3565,004988629,HSK standard course =,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856757,,,20220128.0,...,NYUSH,NYUSH2022275,M,31.50,C,20220126,C,DANGSH,lost; replacement For Spring 2022 Course. [Leon],NaN
3566,008482881,Podcast Marketing: How to Easily Grow Your Aud...,Arrival,20220210.0,HANS,1 new items reported.,31124065545999,CT,"Arrived, but Uncataloged",20220210.0,...,NYUSH,NYUSH2022685,M,14.95,C,20220202,P,AMAZONSH,[Henry],NaN

In [5]:
src.head(10)

,BSN,Z13_TITLE,Z71_TEXT,Z71_OPEN_DATE,Z71_USER_NAME,Z71_DATA,Z30_BARCODE,Z30_ITEM_PROCESS_STATUS,ITEM_PROCESS_STATUS,Z30_PROCESS_STATUS_DATE,...,Z68_ORDERING_UNIT,Z68_ORDER_NUMBER,Z68_ORDER_TYPE,Z68_TOTAL_PRICE,Z68_ARRIVAL_STATUS,Z68_ORDER_STATUS_DATE_X,Z68_INVOICE_STATUS,Z68_VENDOR_CODE,Z68_LIBRARY_NOTE,Unnamed: 24
0,Bibiliographic System Number,Title,Arrival or not,Order Arrival Date,User who marked the item as Arrival,Item(s) Created,Barcode,Item Process Status Code,Item Process Status,IPS Changed Date?,...,Order Unit,Order Number,Order Type,Total Price,Arrival Status,Order Status Date?,Invoice Status,Vendor Code,Library Note,Mateial Format - PRN/VID
1,NaN,NaN,NaN,NaN,Shanghai Staff:,2 new items reported:,NaN,OR,On Order,NaN,...,NaN,NaN,Monograph,NaN,C - Complete,NaN,C - Complete,Local Vendor:,NaN,NaN
2,NaN,NaN,NaN,NaN,HEW,Set or volumns,NaN,GV,Out to vendor for digitization,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,P - Paid,CNP,NaN,NaN
3,NaN,NaN,NaN,NaN,ZHANGY,NaN,NaN,CT,"Arrived, but Uncataloged",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CEPIEC,NaN,NaN
4,NaN,NaN,NaN,NaN,GENERICSH,NaN,NaN,LT,Lost in Cataloging,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SBTSH,NaN,NaN
5,NaN,NaN,NaN,NaN,QIAOZ,NaN,NaN,LB,Labeling,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,CHENVI,NaN,NaN,PT,In transit from KARMS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<blank>,Not in Process,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,004195893,Little rice :,Arrival,20181012.0,HUTCHJ,1 new items reported.,31124057269459,,,20171013.0,...,NYUSH,NYUSH201412815,M,24.94,C,20181012,C,ALIBRISSH,Requested by Sha,NaN
9,005929081,R graphics cookbook :,Arrival,20181129.0,KUYNHK,1 new items reported.,31124063881156,,,20181207.0,...,NYUSH,NYUSH201813,M,0.01,C,20181211,C,AMAZONSH,Preorder. Release Date 4/25/18. Hold for yd627...,NaN

In [14]:
filtered = (src['BSN'].isna()) & (src['Z68_LIBRARY_NOTE'].isna())

In [23]:
filtered_df = src[src['BSN'].notna() & src['Z13_TITLE'].isna()]
filtered

,BSN,Z13_TITLE,Z71_TEXT,Z71_OPEN_DATE,Z71_USER_NAME,Z71_DATA,Z30_BARCODE,Z30_ITEM_PROCESS_STATUS,ITEM_PROCESS_STATUS,Z30_PROCESS_STATUS_DATE,...,Z68_ORDERING_UNIT,Z68_ORDER_NUMBER,Z68_ORDER_TYPE,Z68_TOTAL_PRICE,Z68_ARRIVAL_STATUS,Z68_ORDER_STATUS_DATE_X,Z68_INVOICE_STATUS,Z68_VENDOR_CODE,Z68_LIBRARY_NOTE,Unnamed: 24
1,NaN,NaN,NaN,NaN,Shanghai Staff:,2 new items reported:,NaN,OR,On Order,NaN,...,NaN,NaN,Monograph,NaN,C - Complete,NaN,C - Complete,Local Vendor:,NaN,NaN
2,NaN,NaN,NaN,NaN,HEW,Set or volumns,NaN,GV,Out to vendor for digitization,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,P - Paid,CNP,NaN,NaN
3,NaN,NaN,NaN,NaN,ZHANGY,NaN,NaN,CT,"Arrived, but Uncataloged",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CEPIEC,NaN,NaN
4,NaN,NaN,NaN,NaN,GENERICSH,NaN,NaN,LT,Lost in Cataloging,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SBTSH,NaN,NaN
5,NaN,NaN,NaN,NaN,QIAOZ,NaN,NaN,LB,Labeling,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,CHENVI,NaN,NaN,PT,In transit from KARMS,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<blank>,Not in Process,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
filtered.shape[0]

7

In [6]:
src = src[8:]

In [7]:
src

,BSN,Z13_TITLE,Z71_TEXT,Z71_OPEN_DATE,Z71_USER_NAME,Z71_DATA,Z30_BARCODE,Z30_ITEM_PROCESS_STATUS,ITEM_PROCESS_STATUS,Z30_PROCESS_STATUS_DATE,...,Z68_ORDERING_UNIT,Z68_ORDER_NUMBER,Z68_ORDER_TYPE,Z68_TOTAL_PRICE,Z68_ARRIVAL_STATUS,Z68_ORDER_STATUS_DATE_X,Z68_INVOICE_STATUS,Z68_VENDOR_CODE,Z68_LIBRARY_NOTE,Unnamed: 24
8,004195893,Little rice :,Arrival,20181012.0,HUTCHJ,1 new items reported.,31124057269459,,,20171013.0,...,NYUSH,NYUSH201412815,M,24.94,C,20181012,C,ALIBRISSH,Requested by Sha,NaN
9,005929081,R graphics cookbook :,Arrival,20181129.0,KUYNHK,1 new items reported.,31124063881156,,,20181207.0,...,NYUSH,NYUSH201813,M,0.01,C,20181211,C,AMAZONSH,Preorder. Release Date 4/25/18. Hold for yd627...,NaN
10,005028983,The secret lives of colour /,Arrival,20200115.0,HANS,1 new items reported.,31124063853148,,,20210811.0,...,NYUSH,NYUSH201874,M,22.78,C,20200115,C,AMAZONSH,[CMKM],NaN
11,005910617,B magazine.,Arrival,20190424.0,KOCOGLUA,1 new items reported.,31124063864624,,,20180409.0,...,NYUSH,NYUSH201898,M,162,C,20190424,C,JOHSH,Notify ejl8@nyu.edu [EL],NaN
12,005910617,B magazine.,Arrival,20190424.0,KOCOGLUA,1 new items reported.,31124063864608,,,20180409.0,...,NYUSH,NYUSH201898,M,162,C,20190424,C,JOHSH,Notify ejl8@nyu.edu [EL],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3562,007377413,Republic /,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856740,,,20220128.0,...,NYUSH,NYUSH2022198,M,256.98,C,20220119,C,JDSH,"For Perry, Zee's Spring 2022 course. Ares#5294...",NaN
3563,004988629,HSK standard course =,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856765,,,20220128.0,...,NYUSH,NYUSH2022274,M,70.20,C,20220126,C,DANGSH,lost; replacement For Spring 2022 Course. [Leon],NaN
3564,004988629,HSK standard course =,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856773,,,20220128.0,...,NYUSH,NYUSH2022273,M,70.20,C,20220126,C,DANGSH,lost; replacement For Spring 2022 Course. Are...,NaN
3565,004988629,HSK standard course =,Arrival,20220128.0,ZHANGY,1 new items reported.,31124068856757,,,20220128.0,...,NYUSH,NYUSH2022275,M,31.50,C,20220126,C,DANGSH,lost; replacement For Spring 2022 Course. [Leon],NaN
3566,008482881,Podcast Marketing: How to Easily Grow Your Aud...,Arrival,20220210.0,HANS,1 new items reported.,31124065545999,CT,"Arrived, but Uncataloged",20220210.0,...,NYUSH,NYUSH2022685,M,14.95,C,20220202,P,AMAZONSH,[Henry],NaN

In [21]:
src = src.reset_index(drop=True)

In [26]:
src = src.drop_duplicates()

In [46]:
barcode_duplicates = src['Z30_BARCODE'].duplicated()
barcode_duplicates.name = 'barcode_duplicates'

In [47]:
barcode_duplicates

0       False
1       False
2       False
3       False
4       False
        ...
3554    False
3555    False
3556    False
3557    False
3558    False
Name: barcode_duplicates, Length: 3556, dtype: bool

In [50]:
src = src.join(barcode_duplicates)

In [51]:
src = src[src['barcode_duplicates'] == False]

In [55]:
src = src.drop(src.columns[-2:], axis=1)

In [57]:
src = src.reset_index(drop=True)

In [60]:
src.to_excel("OUTPUT_NYC_REPORT.xlsx", index=False)